FROM mysql:latest as builder

RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

ENV MYSQL_DATABASE=trabalhoppi
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=felipe
ENV MYSQL_PASSWORD=ppi20211

COPY ./scripts/tables.sql /docker-entrypoint-initdb.d

RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db"]

FROM mysql:latest

COPY --from=builder /initialized-db /var/lib/mysql